/pchem-data/meuwly/boittier/home/mmml/setup/charmm
export CHARMM_HOME=/pchem-data/meuwly/boittier/home/mmml/setup/charmm
export CHARMM_LIB_DIR=/pchem-data/meuwly/boittier/home/mmml/setup/charmm
Requirement already satisfied: uv in /pchem-data/meuwly/boittier/home/.local/lib/python3.12/site-packages (0.6.14)
warning: The workspace `requires-python` value (`==3.12`) contains an exact match without a patch version. When omitted, the patch version is implicitly `0` (e.g., `==3.12.0`). Did you mean `==3.12.*`?
Resolved 242 packages in 54ms
Audited 237 packages in 0.85ms
venv activated
venv path: /pchem-data/meuwly/boittier/home/mmml/.venv
venv python path: /pchem-data/meuwly/boittier/home/mmml/.venv/bin/python
UV_ENV_FILE: /pchem-data/meuwly/boittier/home/mmml/CHARMMSETUP
Setup complete
warning: The workspace `requires-python` value (`==3.12`) contains an exact match without a patch version. When omitted, the patch version is implicitly `0` (e.g., `==3.12.0`). Did you mean `==3.12.*`?
Traceback (most recent call last):
  File "/pchem-data/meuwly/boittier/home/mmml/mmml/pycharmm_interface/setupRes.py", line 38, in <module>
    import pycharmm
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/__init__.py", line 17, in <module>
    from .atom_info import get_atom_table
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/atom_info.py", line 24, in <module>
    import pycharmm.coor as coor
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/coor.py", line 31, in <module>
    import pycharmm.lib as lib  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/lib.py", line 67, in <module>
    charmm_lib = CharmmLib(os.environ.get('CHARMM_LIB_DIR', ''))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/lib.py", line 48, in __init__
    self.init_charmm()
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/lib.py", line 58, in init_charmm
    self.lib = ctypes.CDLL(self.charmm_lib_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pchem-data/meuwly/boittier/home/.local/share/uv/python/cpython-3.12.0-linux-x86_64-gnu/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libOpenMM.so.8.1: cannot open shared object file: No such file or directory
Exception ignored in: <function CharmmLib.__del__ at 0x150ff4f33600>
Traceback (most recent call last):
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/lib.py", line 54, in __del__
    self.del_charmm()
  File "/pchem-data/meuwly/boittier/home/mmml/setup/charmm/tool/pycharmm/pycharmm/lib.py", line 62, in del_charmm
    self.lib.del_charmm()  # initiates 'normal stop'
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'del_charmm'
